change `workflow_id` from varchar 255 to text in postgresql
cadence-workflow/cadence pull request #6520
Opened 2024-11-24 17:24 UTC by samuel-lindgren

**What changed?**  
The `workflow_id` column in the PostgreSQL schema has been updated from `VARCHAR(255)` to `TEXT`, removing the 255-character limit and aligning it with Cassandra’s schema, which allows longer workflow identifiers.

**Why?**  
The 255-character limit restricted how much context we could include in workflow identifiers, which was limiting in certain cases. Updating the column to `TEXT` aligns PostgreSQL with Cassandra ([reference](https://github.com/uber/cadence/blob/552953a208c577ef2c0aa10ad8796fbebb1c20af/schema/cassandra/cadence/schema.cql#L40)) and allows higher-level enforcement of length restrictions if needed.

**How did you test it?**  
Not tested yet.

**Potential risks**  
- Longer workflow identifiers could increase database row sizes, potentially impacting performance for workflows with large identifiers.
- Applications relying on the 255-character limit might need adjustments to enforce length restrictions at a higher level.

**Release notes**  
- Schema update: `workflow_id` column in PostgreSQL now uses `TEXT` instead of `VARCHAR(255)`.
- Users relying on the 255-character limit should enforce it at the application level if needed.

**Documentation Changes**  
Not sure if documentation is needed, since these changes will make it more aligned with the Cassandra schema.

2024-11-26 09:24 UTC, samuel-lindgren commented on tools/cli/workflow_batch_commands_test.go
> +					"startTime": "1970-01-01T01:00:01+01:00",
Note, this is just a temporary patch to ensure `POSTGRES=1 make test` works locally for me. This has nothing to do with my changes (I had the same problem with the master branch).

2024-12-02 22:16 UTC, natemort requested changes
LGTM once schema files are updated, thanks for your work on this!

2024-12-02 22:16 UTC, natemort commented on schema/postgres/cadence/versioned/v0.6/extend_workflow_id_length.sql
> +ALTER TABLE executions ALTER workflow_id TYPE text;
Can you also update cadence/schema.sql and visibility/schema.sql to reflect these changes? During first time setup we run only the schema files, the versions are used only when an existing cluster is upgraded. The schema files should match the outcome of running all the version upgrades.

2024-12-05 20:18 UTC, natemort approved these changes

2024-12-05 21:11 UTC, merged